// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spatial.proto

package spatial

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointInPolygonRequest struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointInPolygonRequest) Reset()         { *m = PointInPolygonRequest{} }
func (m *PointInPolygonRequest) String() string { return proto.CompactTextString(m) }
func (*PointInPolygonRequest) ProtoMessage()    {}
func (*PointInPolygonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab81574adde31065, []int{0}
}

func (m *PointInPolygonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointInPolygonRequest.Unmarshal(m, b)
}
func (m *PointInPolygonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointInPolygonRequest.Marshal(b, m, deterministic)
}
func (m *PointInPolygonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointInPolygonRequest.Merge(m, src)
}
func (m *PointInPolygonRequest) XXX_Size() int {
	return xxx_messageInfo_PointInPolygonRequest.Size(m)
}
func (m *PointInPolygonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointInPolygonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointInPolygonRequest proto.InternalMessageInfo

func (m *PointInPolygonRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PointInPolygonRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type StandardPlacesResponse struct {
	Wofid                int64    `protobuf:"varint,1,opt,name=wofid,proto3" json:"wofid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandardPlacesResponse) Reset()         { *m = StandardPlacesResponse{} }
func (m *StandardPlacesResponse) String() string { return proto.CompactTextString(m) }
func (*StandardPlacesResponse) ProtoMessage()    {}
func (*StandardPlacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab81574adde31065, []int{1}
}

func (m *StandardPlacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandardPlacesResponse.Unmarshal(m, b)
}
func (m *StandardPlacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandardPlacesResponse.Marshal(b, m, deterministic)
}
func (m *StandardPlacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandardPlacesResponse.Merge(m, src)
}
func (m *StandardPlacesResponse) XXX_Size() int {
	return xxx_messageInfo_StandardPlacesResponse.Size(m)
}
func (m *StandardPlacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StandardPlacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StandardPlacesResponse proto.InternalMessageInfo

func (m *StandardPlacesResponse) GetWofid() int64 {
	if m != nil {
		return m.Wofid
	}
	return 0
}

func init() {
	proto.RegisterType((*PointInPolygonRequest)(nil), "PointInPolygonRequest")
	proto.RegisterType((*StandardPlacesResponse)(nil), "StandardPlacesResponse")
}

func init() {
	proto.RegisterFile("spatial.proto", fileDescriptor_ab81574adde31065)
}

var fileDescriptor_ab81574adde31065 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x48, 0x2c,
	0xc9, 0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe4, 0x12, 0x0d, 0xc8, 0xcf,
	0xcc, 0x2b, 0xf1, 0xcc, 0x0b, 0xc8, 0xcf, 0xa9, 0x4c, 0xcf, 0xcf, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0xc8, 0x49, 0x2c, 0xc9, 0x2c, 0x29, 0x4d, 0x49, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0a, 0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38, 0x73, 0xf2, 0xf3, 0xd2, 0x21,
	0x92, 0x4c, 0x60, 0x49, 0x84, 0x80, 0x92, 0x1e, 0x97, 0x58, 0x70, 0x49, 0x62, 0x5e, 0x4a, 0x62,
	0x51, 0x4a, 0x40, 0x4e, 0x62, 0x72, 0x6a, 0x71, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa,
	0x90, 0x08, 0x17, 0x6b, 0x79, 0x7e, 0x5a, 0x66, 0x0a, 0xd8, 0x40, 0xe6, 0x20, 0x08, 0xc7, 0xc8,
	0x97, 0x8b, 0x2d, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0x48, 0xc8, 0x99, 0x8b, 0x0f, 0xd5, 0x31, 0x42,
	0x62, 0x7a, 0x58, 0x5d, 0x27, 0x25, 0xae, 0x87, 0xdd, 0x0a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xc7,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x11, 0xc7, 0x84, 0xe9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	PointInPolygon(ctx context.Context, in *PointInPolygonRequest, opts ...grpc.CallOption) (*StandardPlacesResponse, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) PointInPolygon(ctx context.Context, in *PointInPolygonRequest, opts ...grpc.CallOption) (*StandardPlacesResponse, error) {
	out := new(StandardPlacesResponse)
	err := c.cc.Invoke(ctx, "/Server/PointInPolygon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	PointInPolygon(context.Context, *PointInPolygonRequest) (*StandardPlacesResponse, error)
}

// UnimplementedServerServer can be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (*UnimplementedServerServer) PointInPolygon(ctx context.Context, req *PointInPolygonRequest) (*StandardPlacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PointInPolygon not implemented")
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_PointInPolygon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointInPolygonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).PointInPolygon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Server/PointInPolygon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).PointInPolygon(ctx, req.(*PointInPolygonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PointInPolygon",
			Handler:    _Server_PointInPolygon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spatial.proto",
}
